### PR TITLE
need to take the region from firehoseOptions - not options

### PR DESCRIPTION
**Pull request by alfasin**
take the param from the right place

### CODE REVIEW

**Comment by alfasin** [comment]
Sorry about that...

**Comment by pkallos** [comment]
np, I missed it also ... :)

**Comment by pkallos** [comment]
This is now published as [v2.0.3](https://www.npmjs.com/package/winston-firehose/v/2.0.3).

**Comment by pkallos** [comment]
@alfasin this working as expected now?

**Comment by alfasin** [comment]
Yes - thanks!!!

**Pull request merged**
